### ISSUE TITLE
Add redis caching for Athena queries.

### ISSUE THREAD

**Issue by BTurkowyd** [BTurkowyd/personal-gym-tracker#41]
Not done in #37 but still worth doing to save money. Add Redis caching backend.

docker-compose:
```
  redis:
    image: redis:6-alpine
    container_name: superset_redis
    ports:
      - "6379:6379"
    networks:
      - superset-network

superset part:
      SUPERSET_CELERY_BROKER_URL: "redis://redis:6379/0"
      SUPERSET_CELERY_RESULT_BACKEND: "redis://redis:6379/0"
      CACHE_CONFIG: '{"CACHE_TYPE": "RedisCache", "CACHE_DEFAULT_TIMEOUT": 300, "CACHE_KEY_PREFIX": "superset_", "CACHE_REDIS_URL": "redis://redis:6379/0"}'
    
```
